# Generated by Django 4.2.13 on 2026-06-11 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoEstadoCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('concepto', models.CharField(max_length=255, verbose_name='Concepto')),
                ('numero_documento', models.CharField(blank=True, default='', max_length=50, verbose_name='N° Documento')),
                ('debito', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Débito')),
                ('credito', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Crédito')),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Saldo')),
                ('archivo_original', models.CharField(blank=True, default='', max_length=255, verbose_name='Archivo de origen')),
                ('fecha_importacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de importación')),
            ],
            options={
                'verbose_name': 'Movimiento de Estado de Cuenta',
                'verbose_name_plural': 'Movimientos de Estado de Cuenta',
                'ordering': ['fecha', 'pk'],
            },
        ),
    ]
