# Generated by Django 4.2.13 on 2026-06-13 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estado_cuenta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoImportado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='estados_cuenta/', verbose_name='Archivo')),
                ('nombre_original', models.CharField(max_length=255, verbose_name='Nombre original')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
                ('total_movimientos', models.PositiveIntegerField(default=0, verbose_name='Total de movimientos')),
            ],
            options={
                'verbose_name': 'Archivo importado',
                'verbose_name_plural': 'Archivos importados',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.AddField(
            model_name='movimientoestadocuenta',
            name='archivo_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='estado_cuenta.archivoimportado', verbose_name='Archivo de origen'),
        ),
    ]
