# Generated by Django 4.2.13 on 2026-06-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estado_cuenta', '0002_archivoimportado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimientoestadocuenta',
            options={'ordering': ['-producto', 'nit'], 'verbose_name': 'Declaración de Estado de Cuenta', 'verbose_name_plural': 'Declaraciones de Estado de Cuenta'},
        ),
        migrations.RemoveField(
            model_name='movimientoestadocuenta',
            name='concepto',
        ),
        migrations.RemoveField(
            model_name='movimientoestadocuenta',
            name='credito',
        ),
        migrations.RemoveField(
            model_name='movimientoestadocuenta',
            name='debito',
        ),
        migrations.RemoveField(
            model_name='movimientoestadocuenta',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='movimientoestadocuenta',
            name='numero_documento',
        ),
        migrations.RemoveField(
            model_name='movimientoestadocuenta',
            name='saldo',
        ),
        migrations.AddField(
            model_name='movimientoestadocuenta',
            name='autorizado_por',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Autorizado por'),
        ),
        migrations.AddField(
            model_name='movimientoestadocuenta',
            name='ejecutado_por',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Ejecutado por'),
        ),
        migrations.AddField(
            model_name='movimientoestadocuenta',
            name='impuesto_inicial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Impuesto Inicial'),
        ),
        migrations.AddField(
            model_name='movimientoestadocuenta',
            name='impuesto_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Impuesto Total'),
        ),
        migrations.AddField(
            model_name='movimientoestadocuenta',
            name='nit',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='NIT'),
        ),
        migrations.AddField(
            model_name='movimientoestadocuenta',
            name='persona_fiscal',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Persona Fiscal'),
        ),
        migrations.AddField(
            model_name='movimientoestadocuenta',
            name='principal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Principal'),
        ),
        migrations.AddField(
            model_name='movimientoestadocuenta',
            name='producto',
            field=models.DateField(blank=True, null=True, verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='movimientoestadocuenta',
            name='prox_hacienda',
            field=models.DateField(blank=True, null=True, verbose_name='Próx. Hacienda'),
        ),
        migrations.AddField(
            model_name='movimientoestadocuenta',
            name='recargo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Recargo'),
        ),
        migrations.AddField(
            model_name='movimientoestadocuenta',
            name='referencia',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Referencia'),
        ),
        migrations.AddField(
            model_name='movimientoestadocuenta',
            name='sucursal',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Sucursal'),
        ),
        migrations.AddField(
            model_name='movimientoestadocuenta',
            name='tipo',
            field=models.IntegerField(default=0, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='movimientoestadocuenta',
            name='tipo_impuesto',
            field=models.IntegerField(default=10, verbose_name='Tipo de Impuesto'),
        ),
    ]
