# Generated by Django 4.2.13 on 2026-06-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estado_cuenta', '0003_alter_movimientoestadocuenta_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoestadocuenta',
            name='autorizado_por',
            field=models.CharField(max_length=255, verbose_name='Autorizado por'),
        ),
        migrations.AlterField(
            model_name='movimientoestadocuenta',
            name='ejecutado_por',
            field=models.CharField(max_length=255, verbose_name='Ejecutado por'),
        ),
        migrations.AlterField(
            model_name='movimientoestadocuenta',
            name='nit',
            field=models.CharField(max_length=20, verbose_name='NIT'),
        ),
        migrations.AlterField(
            model_name='movimientoestadocuenta',
            name='persona_fiscal',
            field=models.CharField(max_length=255, verbose_name='Persona Fiscal'),
        ),
        migrations.AlterField(
            model_name='movimientoestadocuenta',
            name='producto',
            field=models.DateField(verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='movimientoestadocuenta',
            name='prox_hacienda',
            field=models.DateField(verbose_name='Próx. Hacienda'),
        ),
        migrations.AlterField(
            model_name='movimientoestadocuenta',
            name='referencia',
            field=models.CharField(max_length=255, verbose_name='Referencia'),
        ),
        migrations.AlterField(
            model_name='movimientoestadocuenta',
            name='sucursal',
            field=models.CharField(max_length=50, verbose_name='Sucursal'),
        ),
    ]
