# Generated by Django 4.2.13 on 2026-06-02 15:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribuciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribuyente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carnet_identidad', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'Debe tener exactamente 11 dígitos numéricos.')], verbose_name='Carnet de Identidad')),
                ('numero_contribuyente', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Este campo solo admite dígitos numéricos.', regex='^\\d+$')], verbose_name='Número de Contribuyente')),
                ('codigo_zpc', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Código ZPC inválido. Use letras mayúsculas, números y guiones (3–20 caracteres).', regex='^[A-Z0-9\\-]{3,20}$')], verbose_name='Código ZPC')),
                ('tipo_cuenta', models.CharField(choices=[('natural', 'Natural'), ('fiscal', 'Fiscal')], max_length=10, verbose_name='Tipo de Cuenta')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contribuyente',
                'verbose_name_plural': 'Contribuyentes',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
