# Generated by Django 4.2.13 on 2026-06-04 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribuciones', '0002_contribuyente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribucion',
            name='obligacion_pago',
            field=models.CharField(choices=[('contribucion_mensual_patrimonio', 'Contribución mensual patrimonio'), ('donaciones', 'Donaciones')], max_length=100, verbose_name='Obligación de Pago'),
        ),
    ]
