# Generated by Django 4.2.13 on 2026-06-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribuciones', '0005_alter_contribucion_tipo_cuenta'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribuyente',
            name='nombre',
            field=models.CharField(blank=True, default='', help_text='Nombre completo (persona natural) o nombre de la entidad (cuenta fiscal).', max_length=255, verbose_name='Nombre del Contribuyente'),
        ),
    ]
