# Generated by Django 4.2.13 on 2026-06-11 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribuciones', '0006_contribuyente_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribucion',
            name='nombre',
            field=models.CharField(blank=True, default='', help_text='Nombre completo (persona natural) o nombre de la entidad (cuenta fiscal).', max_length=255, verbose_name='Nombre del Contribuyente'),
        ),
    ]
