# Generated by Django 4.2.13 on 2026-06-11 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribuciones', '0007_contribucion_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribucion',
            name='obligacion_pago',
            field=models.CharField(choices=[('contribucion', 'Contribución'), ('donacion', 'Donación')], max_length=100, verbose_name='Obligación de Pago'),
        ),
    ]
