# Generated by Django 4.2.13 on 2026-06-11 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contribuciones', '0008_alter_contribucion_obligacion_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organismo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True, verbose_name='Nombre del Organismo')),
            ],
            options={
                'verbose_name': 'Organismo',
                'verbose_name_plural': 'Organismos',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='contribucion',
            name='direccion',
            field=models.CharField(blank=True, default='', help_text='Calle y entrecalles donde radica el contribuyente.', max_length=255, verbose_name='Dirección (calle y entrecalles)'),
        ),
        migrations.AddField(
            model_name='contribucion',
            name='nombre_establecimiento',
            field=models.CharField(blank=True, default='', help_text='Nombre del establecimiento o entidad.', max_length=255, verbose_name='Nombre del Establecimiento'),
        ),
        migrations.AddField(
            model_name='contribuyente',
            name='direccion',
            field=models.CharField(blank=True, default='', help_text='Calle y entrecalles donde radica el contribuyente.', max_length=255, verbose_name='Dirección (calle y entrecalles)'),
        ),
        migrations.AddField(
            model_name='contribuyente',
            name='nombre_establecimiento',
            field=models.CharField(blank=True, default='', help_text='Nombre del establecimiento o entidad.', max_length=255, verbose_name='Nombre del Establecimiento'),
        ),
        migrations.AddField(
            model_name='contribucion',
            name='organismo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contribuciones', to='contribuciones.organismo', verbose_name='Organismo'),
        ),
        migrations.AddField(
            model_name='contribuyente',
            name='organismo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contribuyentes', to='contribuciones.organismo', verbose_name='Organismo'),
        ),
    ]
