apiVersion: v1
kind: Secret
metadata:
  name: django-secret
  namespace: patrimonio
type: Opaque
stringData:
  SECRET_KEY: "67@e8=)yp*_@d7*aeb5=i_%2+wi&o%n7@p9(*b2sj@wi(81pmn"
  DB_PASSWORD: "bjfree12"
